services:
  web:
    image: webdevops/php-apache:8.4
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    env_file:
      - .env
  db:
    image: mariadb:12.0.2
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}